#!/bin/bash

echo "=== PostgreSQL Deployment Guide for Render ==="
echo ""
echo "1. Create a PostgreSQL database on Render:"
echo "   - Go to your Render dashboard"
echo "   - Click 'New' -> 'PostgreSQL'"
echo "   - Name: vpn-bot-db"
echo "   - Plan: Free"
echo "   - Click 'Create Database'"
echo ""
echo "2. Get the database connection string:"
echo "   - In your database dashboard, copy the 'External Database URL'"
echo "   - It should look like: postgresql://user:password@host:port/database"
echo ""
echo "3. Set environment variables in your web service:"
echo "   - Go to your vpn-bot web service"
echo "   - Add environment variable:"
echo "     Key: DATABASE_URL"
echo "     Value: [paste the connection string from step 2]"
echo "   - Add environment variable:"
echo "     Key: USE_POSTGRESQL"
echo "     Value: true"
echo ""
echo "4. Deploy your application:"
echo "   - Push your code to trigger a new deployment"
echo "   - The application will automatically initialize the PostgreSQL database"
echo ""
echo "5. Optional: Run migration script locally to transfer existing data:"
echo "   python migrate_to_postgresql.py"
echo ""
echo "=== Deployment Complete ===" 