#!/bin/bash

echo "🚀 VLESS Bot VPS Testing Script"
echo "================================"

echo ""
echo "📋 Steps to test the VLESS bot on your VPS:"
echo ""
echo "1. SSH to your VPS:"
echo "   ssh root@77.110.110.205"
echo ""
echo "2. Navigate to bot directory:"
echo "   cd /opt/vless_bot"
echo ""
echo "3. Activate virtual environment:"
echo "   source venv/bin/activate"
echo ""
echo "4. Test the bot:"
echo "   python vless_only_bot.py"
echo ""
echo "5. If it works, set up as service:"
echo "   sudo systemctl start vless-bot"
echo "   sudo systemctl status vless-bot"
echo ""
echo "6. View logs:"
echo "   sudo journalctl -u vless-bot -f"
echo ""
echo "🎯 Expected behavior:"
echo "   - Bot should start without errors"
echo "   - Should show 'Starting VLESS-only bot...'"
echo "   - Should connect to Xray API on 127.0.0.1:62789"
echo ""
echo "📱 Test commands in Telegram:"
echo "   /start - Should show welcome message"
echo "   /help - Should show help"
echo "   /vless_subscribe - Should create VLESS user and return URI"
echo ""
echo "🔧 If there are errors:"
echo "   - Check .env file has correct bot token"
echo "   - Check Xray is running: systemctl status xray"
echo "   - Check Xray API port: netstat -tlnp | grep 62789"
echo ""
echo "Ready to test! 🚀" 